### PR TITLE
Corba aliases

### PR DESCRIPTION
**Pull request by smits**
This PR allows to create CORBA component servers that instead of using their own name, use an alias.  This is handy if you have X similar deployments in which you do not want to do component renaming for various reasons but you still want to remotely connect to multiple of them.  In this case registering them under an alias allows you to create remote proxies that remotely will be known under their alias name.

### CODE REVIEW

**Comment by psoetens** [comment]
I agree that this needs refactoring...

**Comment by smits** [comment]
I refactored and tested again. Please reconsider merging ;)

**Comment by snrkiwi** [comment]
While I agree with _meyerj_ that _comps_ may not be needed, it seems that unwinding it from all the deployment code could be a bad thing. It's used in almost 80 different places. I'd argue for leaving it in for now, and perhaps dealing with it later?

**Comment by smits** [comment]
I agree with @snrkiwi , refactoring out the comps could be part of another PR.

**Comment by meyerj** [comment]
merged into toolchain-2.9: 5699152daf57c776c8f49b1a644df2686e48fd80

**Pull request merged**
