### PR TITLE
Tlsf memory corruption detection

### PR DESCRIPTION
**Pull request by smits**
Reopening PR #63

### CODE REVIEW

**Comment by snrkiwi** [comment]
Any reason that this hasn't been merged? We've been using this for months on operational systems ...

**Comment by smits** [comment]
The only reason is that ATM it aborts your application, it's uncertain yet if this is really what everyone wants.

**Comment by snrkiwi** [comment]
Ok, so who makes the decision to merge it or not? Let's either merge, change it, or discard it, rather than leaving it hanging.

**Comment by meyerj** [comment]
merged into toolchain-2.9: 87220dc1ec9000c6cb57bb8c53c6775be8991fbd

**Pull request merged**
