### PR TITLE
add aarch64 support

### PR DESCRIPTION
**Pull request by ahoarau**
This just add support for the aarch64 tag (arm64).
Sorry for the patch-1 name, I did it with the web interface.

### CODE REVIEW

**Comment by meyerj** [comment]
I could not find any usage of these macros within RTT except for [rtt/os/oro_arch.h](https://github.com/ahoarau/rtt/blob/d1efde9efee66f8db418674688ca3df9221a3b97/rtt/os/oro_arch.h), but there is no special case for the ARM architecture anyway. What is the effect of the added tag? Only for derived packages?

**Comment by meyerj** [comment]
Build failure on Travis would be fixed by #215.

**Comment by ahoarau** [comment]
I don't use it, but it's necessary otherwise it send an error "unknown processor architecture".

**Comment by ahoarau** [comment]
Thanks for this ! Does it mean rtt (+everything else) will be available in the arm64v8 build farm ?

**Comment by ahoarau** [comment]
@meyerj aby way to trigger the debian build for aarch64 (arm64v8) ?

**Pull request merged**
