### PR TITLE
boost lambda ist not working for boost 1.57 and clang 3.4, 3.5, 3.6, …

### PR DESCRIPTION
**Pull request by malter**

### CODE REVIEW

**Comment by goldhoorn** [comment]
no negative impact on linux, okay then for merge for me

**Comment by snrkiwi** [comment]
The option definition in the root CMakeLists.txt file should go *after* the section in that file that loads the "orocos-rtt.cmake" override file, allowing projects to set the option in the override file without having to modify the root CMakeLists.txt file.

**Comment by smits** [comment]
Tested this on Ubuntu 10.04, 14.04 and OSX 10.8.5. LGTM

**Comment by smits** [comment]
@malter , I agree with @snrkiwi , could you update your PR?

**Comment by goldhoorn** [comment]
@malter is not available the next month. I could superseed the PR if you want.

**Comment by smits** [comment]
@goldhoorn : fine for me

**Comment by goldhoorn** [comment]
I created the new PR, please continue (or merge) the discussion there 
https://github.com/orocos-toolchain/rtt/pull/103

**Pull request closed without merging**
